# Generated by Django 3.2.25 on 2025-06-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('wishlist', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=20)),
                ('tags', models.TextField(default=list)),
                ('category', models.CharField(choices=[('product', 'Product'), ('supplement', 'Supplement')], default='product', max_length=20)),
            ],
        ),
    ]
